name: Assign Issues to Project Board

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Assign issue to project board
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label ? context.payload.label.name : null;
            const projectId = '4'; // Replace with your project ID
            const columnMapping = {
              'bug': 'Issue',
              'addon': 'Suggestions',
              'enhancement': 'Suggestions'
            };

            if (!label || !columnMapping[label]) {
              console.log('Label does not match any of the specified labels.');
              return;
            }

            const status = columnMapping[label];

            const { data: projectCards } = await github.projects.listCards({
              column_id: projectId,
              archived_state: 'not_archived'
            });

            const card = projectCards.find(card => card.content_url === issue.url);

            if (card && card.column_id === 'No status') {
              await github.projects.moveCard({
                card_id: card.id,
                position: 'top',
                column_id: status
              });
              console.log(`Moved issue #${issue.number} to ${status} column.`);
            } else {
              console.log(`Issue #${issue.number} is already in a different column.`);
            }