name: Assign Issue to Project

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Assign issue to project column and update card status fields
        if: github.event.label.name == 'bug' || github.event.label.name == 'addon' || github.event.label.name == 'enhancement'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: 4
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          LABEL=${{ github.event.label.name }}

          if [ "$LABEL" == "bug" ]; then
            COLUMN_NAME="Issue"
          elif [ "$LABEL" == "addon" ] || [ "$LABEL" == "enhancement" ]; then
            COLUMN_NAME="Suggestions"
          fi

          # Get the column ID based on the column name
          COLUMN_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                           -H "Accept: application/vnd.github.inertia-preview+json" \
                           https://api.github.com/repos/$REPO/projects/$PROJECT_ID/columns | \
                     jq -r --arg COLUMN_NAME "$COLUMN_NAME" '.[] | select(.name == $COLUMN_NAME) | .id')

          # Create a project card for the issue
          CARD_ID=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/$COLUMN_ID/cards \
            -d "{\"content_id\": $ISSUE_NUMBER, \"content_type\": \"Issue\"}" | jq -r '.id')

          # Update the card status fields (replace FIELD_ID and VALUE with actual values)
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/cards/$CARD_ID \
            -d "{\"note\": \"Status: Open\"}" # Replace with actual status field update