name: Assign Issue to Status Based on Label

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Assign status based on label
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PROJECT_ID: PVT_kwHOAo7FNc4AzGK0
        run: |
          node -e "
          const { graphql } = require('@octokit/graphql');
          const graphqlWithAuth = graphql.defaults({
            headers: {
              authorization: `token ${process.env.TOKEN}`
            }
          });

          async function run() {
            const context = require(process.env.GITHUB_EVENT_PATH);
            const issue = context.issue;
            const labels = issue.labels.map(label => label.name);

            console.log('Issue labels:', labels);

            let status = 'Issue'; // Default status
            if (labels.includes('bug')) {
              status = 'Issue';
            } else if (labels.includes('addon')) {
              status = 'Suggestions';
            } else if (labels.includes('enhancement')) {
              status = 'Suggestions';
            }

            console.log('Determined status:', status);

            // Fetch columns using GraphQL
            const query = `
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    id
                    title
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2Field {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;

            const result = await graphqlWithAuth(query, {
              projectId: process.env.PROJECT_ID
            });

            console.log('Project columns:', result.node.fields.nodes);

            const column = result.node.fields.nodes.find(col => col.name === status);
            if (!column) {
              throw new Error(`Column with status ${status} not found`);
            }

            console.log('Found column:', column);

            // Create card in the column
            const mutation = `
              mutation($columnId: ID!, $issueId: ID!) {
                addProjectV2ItemById(input: {projectId: $columnId, contentId: $issueId}) {
                  item {
                    id
                  }
                }
              }
            `;

            await graphqlWithAuth(mutation, {
              columnId: column.id,
              issueId: issue.id
            });

            console.log('Card created in column:', column.name);
          }

          run().catch(error => console.error('Error:', error));
          "