name: Assign Issue to Project Status

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Assign issue to project status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const projectId = 'PVT_kwHOAo7FNc4AzGK0';
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const labels = context.payload.issue.labels.map(label => label.name);
            let status = '';

            if (labels.includes('bug')) {
              status = 'To Do';
            } else if (labels.includes('enhancement')) {
              status = 'In Progress';
            } else if (labels.includes('question')) {
              status = 'Done';
            }

            if (status) {
              const project = await github.projects.getProject({
                project_id: projectId
              });

              const columns = await github.projects.listColumns({
                project_id: projectId
              });

              const column = columns.data.find(col => col.name === status);

              if (column) {
                await github.projects.createCard({
                  column_id: column.id,
                  content_id: context.payload.issue.id,
                  content_type: 'Issue'
                });
              }
            }