name: Assign Issue to Status Based on Label

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Bug label
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/PSYCHEER/projects/4"
          column-name: "Issue"
          label-name: "bug"
          columns-to-ignore: "Suggestions, In progress, Ready, Done"

      - name: Addon label
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/PSYCHEER/projects/4"
          column-name: "Suggestions"
          label-name: "addon"
          columns-to-ignore: "Issue, In progress, Ready, Done"

      - name: Enhancement label
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/PSYCHEER/projects/4"
          column-name: "Suggestions"
          label-name: "enhancement"
          columns-to-ignore: "Issue, In progress, Ready, Done"