name: Assign Issue to Status Based on Label

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run assign status script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PROJECT_ID: PVT_kwHOAo7FNc4AzGK0
        run: node assign-status.js