name: Assign Issue to Project

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Assign issue to project column
        if: github.event.label.name == 'bug' || github.event.label.name == 'addon' || github.event.label.name == 'enhancement'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: 4
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          LABEL=${{ github.event.label.name }}

          if [ "$LABEL" == "bug" ]; then
            COLUMN_ID=12345678 # Replace with the actual column ID for "Issue"
          elif [ "$LABEL" == "addon" ] || [ "$LABEL" == "enhancement" ]; then
            COLUMN_ID=87654321 # Replace with the actual column ID for "Suggestions"
          fi

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/$COLUMN_ID/cards \
            -d "{\"content_id\": $ISSUE_NUMBER, \"content_type\": \"Issue\"}"