name: Assign Issues to Project

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue labels
      id: check_labels
      uses: actions/github-script@v6
      with:
        script: |
          const labels = context.payload.issue.labels.map(label => label.name.toLowerCase());
          const hasAddon = labels.includes('addon');
          const hasEnhancement = labels.includes('enhancement');
          console.log(`Labels: ${labels}`);
          console.log(`Has Addon: ${hasAddon}`);
          console.log(`Has Enhancement: ${hasEnhancement}`);
          core.setOutput("hasAddon", hasAddon);
          core.setOutput("hasEnhancement", hasEnhancement);

    - name: Debug outputs
      run: |
        echo "Has Addon: ${{ steps.check_labels.outputs.hasAddon }}"
        echo "Has Enhancement: ${{ steps.check_labels.outputs.hasEnhancement }}"

    - name: Assign to project
      if: steps.check_labels.outputs.hasAddon == 'true' || steps.check_labels.outputs.hasEnhancement == 'true'
      uses: actions/github-script@v6
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        script: |
          const fetch = require('node-fetch');

          async function assignIssueToProject() {
            const projectUrl = 'https://api.github.com/users/PSYCHEER/projects/4';
            const columnName = 'Suggestions';
            const issueUrl = context.payload.issue.html_url;

            console.log(`Assigning issue to project: ${projectUrl}`);
            console.log(`Column name: ${columnName}`);

            const projectId = projectUrl.split('/').pop();

            const ▋