name: Reassign Issue Based on Label

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]


jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List issues assigned to the project
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo '{
            "query": "query { 
              node(id: \\"PVT_kwHOAo7FNc4AzGK0\\") { 
                ... on ProjectV2 { 
                  items(first: 100) { 
                    nodes { 
                      content { 
                        ... on Issue { 
                          title 
                          number 
                          assignees(first: 10) { 
                            nodes { 
                              login 
                            } 
                          } 
                        } 
                      } 
                    } 
                  } 
                } 
              } 
            }"
          }' > query.json

          curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -d @query.json \
                https://api.github.com/graphql \
                | jq '.data.node.items.nodes[].content | {title, number, assignees: .assignees[].login}'