name: Bug to project

on:
  issues:
    types: [labeled]

jobs:
  assign_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Bug label
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Issue"
          target-labels: "bug"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"