name: Close Issues

on:
  issues:
    types:
      - labeled

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        if: |
            contains(github.event.label.name, 'invalid')
        uses: peter-evans/close-issue@v3
        with:
            issue-number: ${{ github.event.issue.number }}
            comment: Auto-closed
            token: ${{ secrets.TOKEN }}
      - name: Close duplicate
        if: |
            contains(github.event.label.name, 'duplicate')
        uses: peter-evans/close-issue@v3
        with:
            issue-number: ${{ github.event.issue.number }}
            comment: Auto-closed
            token: ${{ secrets.TOKEN }}
      - name: Not Planned
        if: contains(github.event.label.name, 'not_planned')
        uses: peter-evans/close-issue@v3
        with:
            issue-number: ${{ github.event.issue.number }}
            comment: Auto-closed
            close-reason: not_planned
            token: ${{ secrets.TOKEN }}
