name: Close Issues

on:
  issues:
    types:
      - labeled

jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.label.name, 'invalid') ||
      contains(github.event.label.name, 'duplicate') ||
      contains(github.event.label.name, 'not planned')
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
            issue-number: ${{ github.event.issue.number }}
            comment: Auto-closed
            labels: invalid, duplicate, not planned
            token: ${{ secrets.GITHUB_TOKEN }}