name: Addon to project

on:
  issues:
    types: [labeled]

jobs:
  assign_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Check if issue has 'addon' or 'bug' label
        id: check_label
        run: |
          labels=$(jq -r '.issue.labels[].name' $GITHUB_EVENT_PATH)
          echo "labels=$labels" >> $GITHUB_ENV
          if echo "$labels" | grep -q "addon"; then
            echo "label=addon" >> $GITHUB_OUTPUT
          elif echo "$labels" | grep -q "bug"; then
            echo "label=bug" >> $GITHUB_OUTPUT
          elif echo "$labels" | grep -q "enhancement"; then
            echo "label=enhancement" >> $GITHUB_OUTPUT
          elif echo "$labels" | grep -q "candidate"; then
            echo "label=candidate" >> $GITHUB_OUTPUT
          elif echo "$labels" | grep -q "documentation"; then
            echo "label=documentation" >> $GITHUB_OUTPUT
          else
            echo "Label is neither 'addon', 'enhancement' nor 'bug'. Exiting."
            exit 0
          fi

      - name: Addon label
        if: steps.check_label.outputs.label == 'addon'
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Suggestions"
          target-labels: "addon"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"

      - name: Enhancement label
        if: steps.check_label.outputs.label == 'enhancement'
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Suggestions"
          target-labels: "enhancement"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"
      
      - name: Bug label
        if: steps.check_label.outputs.label == 'bug'
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Issue"
          target-labels: "bug"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"

      - name: Candidate label
        if: steps.check_label.outputs.label == 'candidate'
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Ready"
          target-labels: "candidate"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"

      - name: Documentation label
        if: steps.check_label.outputs.label == 'documentation'
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: "${{ secrets.TOKEN }}"
          project-url: "https://github.com/users/PSYCHEER/projects/4"
          target-column: "Suggestions"
          target-labels: "documentation"
          default-column: "Issue"
          ignored-columns: "In progress, Ready, Done"